#!/bin/sh
#
# Copyright (c) 2008 Owen Williams
# You may use and distribute this software under the terms of the
# GNU General Public License, version 2 or later
#

HILDON=0
if [ -f "/usr/lib/libgtkembedmoz.so.0" -a -d "/usr/lib/microb-engine" ]; then
	HILDON=1
	echo "Launching Hildon version"
	export MOZILLA_FIVE_HOME="/usr/lib/microb-engine"
	export LD_LIBRARY_PATH="/usr/lib/microb-engine"
else
	have_home=0
	if [ x$MOZILLA_FIVE_HOME != "x" ] ; then
		if [ -d $MOZILLA_FIVE_HOME ] ; then
			echo "Using existing MOZILLA_FIVE_HOME: $MOZILLA_FIVE_HOME"
			export LD_LIBRARY_PATH=$MOZILLA_FIVE_HOME
			have_home=1
		else
			echo "MOZILLA_FIVE_HOME set but invalid: $MOZILLA_FIVE_HOME"
		fi
	fi
	
	if [ $have_home -eq 0 ] ; then
		for moz in "xulrunner-gtkmozembed" "firefox-gtkmozembed" "mozilla-gtkmozembed"; do
			home=`pkg-config --silence-errors --libs-only-L $moz | sed 's/ //g'`
			if [ "x"$home != "x" ] ; then
				home=`echo $home | sed -e 's/-L//;'`
				if [ ! -d $home ] ; then
					echo "Thought mozilla was in $home, but path doesn't exist"
					echo "Error finding MOZILLA_FIVE_HOME, please set it yourself"
					exit 1
				fi
				echo Found gtkmozembed in $home
				export MOZILLA_FIVE_HOME=$home
				export LD_LIBRARY_PATH=$home
				break	
			fi
		done
	fi
fi

rundir=`dirname $0`


ptv_home=`/usr/bin/env python -c "import os, sys; 
if os.environ.has_key('PENGUINTV_LIB'): 
    print os.environ['PENGUINTV_LIB'];  
    sys.exit(0); 
for d in [\"$rundir\"] + sys.path:
    if d[0] == '.':
        d = os.path.join(os.getcwd(), d);
    sd = os.path.join(d, 'penguintv'); 
    if os.path.isdir(sd):
        print sd; 
        sys.exit(0); 
h, t = os.path.split(os.path.split(os.path.abspath(sys.argv[0]))[0]); 
if t == 'bin': 
    libdir = os.path.join(h, 'lib'); 
    fp = os.path.join(libdir, 'penguintv'); 
    if os.path.isdir(fp): 
        print libdir; 
        sys.exit(0); 
sys.exit(1)"`

if [ $? -gt 0 ] ; then
	echo "Error finding PenguinTV library home.  Please export PENGUINTV_LIB"
	exit 1
fi

if [ $HILDON -eq 1 ] ; then
	echo "Running ptv in $ptv_home"
	run-standalone.sh python2.5 -c "import sys; \
sys.path.insert(0, \"$ptv_home\");
import penguintv;
import utils;

penguintv.main()"
else
	/usr/bin/env python -c "import os, sys;
os.chdir(\"$ptv_home\");
sys.path.insert(0, \"$ptv_home\");

import penguintv;
import utils;

#import cProfile;
#cProfile.run('penguintv.main()', '/tmp/penguintv-prof');
#sys.exit(0);
penguintv.main()"
fi
