#!/bin/sh

if [ -f "/usr/lib/libgtkembedmoz.so" -a -d "/usr/lib/microb-engine" ]; then
	echo "Launching Hildon version"
	export MOZILLA_FIVE_HOME="/usr/lib/microb-engine"
	export LD_LIBRARY_PATH="/usr/lib/microb-engine"
	run-standalone.sh python2.5 -c "import sys; \
sys.path.insert(0, \"/usr/lib/python2.5/site-packages/penguintv\");
import penguintv;
import utils;

penguintv.main()"
	exit 0
else
	have_home=0
	if [ x$MOZILLA_FIVE_HOME != "x" ] ; then
		if [ -d $MOZILLA_FIVE_HOME ] ; then
			echo "Using existing MOZILLA_FIVE_HOME: $MOZILLA_FIVE_HOME"
			export LD_LIBRARY_PATH=$MOZILLA_FIVE_HOME
			have_home=1
		else
			echo "MOZILLA_FIVE_HOME set but invalid: $MOZILLA_FIVE_HOME"
		fi
	fi
	
	if [ $have_home = 0 ] ; then
		for moz in "xulrunner-gtkmozembed" "firefox-gtkmozembed" "mozilla-gtkmozembed"; do
			home=`pkg-config --silence-errors --libs-only-L $moz | sed 's/ //g'`
			if [ x"$home" != "x" ] ; then
				home=${home:2}
				if [ ! -d $home ] ; then
					echo "Thought mozilla was in $home, but path doesn't exist"
					echo "Error finding MOZILLA_FIVE_HOME, please set it yourself"
					exit 1
				fi
				echo Found gtkmozembed in $home
				export MOZILLA_FIVE_HOME=$home
				export LD_LIBRARY_PATH=$home
				break	
			fi
		done
	fi
fi


ptv_home=`/usr/bin/env python -c "import os, sys; 
if os.environ.has_key('PENGUINTV_LIB'): 
    print os.environ['PENGUINTV_LIB'];  
    sys.exit(0); 
for d in sys.path: 
    sd = os.path.join(d, 'penguintv'); 
    if os.path.isdir(sd):
        if d == '':
    	    print os.path.join(os.getcwd(), 'penguintv');
    	    sys.exit(0);
        print sd; 
        sys.exit(0); 
h, t = os.path.split(os.path.split(os.path.abspath(sys.argv[0]))[0]); 
if t == 'bin': 
    libdir = os.path.join(h, 'lib'); 
    fp = os.path.join(libdir, 'penguintv'); 
    if os.path.isdir(fp): 
        print libdir; 
        sys.exit(0); 
sys.exit(1)"`

if [ $? -gt 0 ] ; then
	echo "Error finding PenguinTV library home.  Please export PENGUINTV_LIB"
	exit 1
fi

echo "Using penguintv found in $ptv_home"

/usr/bin/env python -c "import sys; \
sys.path.insert(0, \"$ptv_home\");
import penguintv;
import utils;

penguintv.main()"

